language: nodejs
dist: bionic
services: docker

node_js:
  - 12

before_install:
- node --version
- npm --version

install:
- npm install
- docker-compose -f docker/docker-compose.yml pull
- docker-compose -f docker/docker-compose.yml build

before_script:
- docker-compose -f docker/docker-compose.yml up -d
- npm run serve &

script:
- npm run test
