language: node_js
dist: bionic
services:
  - docker

node_js:
  - 10

install:
  - npm install
  - docker-compose -f docker/docker-compose.yml pull
  - docker-compose -f docker/docker-compose.yml build

before_script:
  - docker-compose -f docker/docker-compose.yml up -d
  - npm run serve &

script:
  - npm run test
