language: node_js
dist: bionic
services:
  - docker

node_js:
  - 10

cache:
  directories:
    - node_modules

install:
  - yarn install --freeze
  - docker-compose -f docker/docker-compose.yml pull
  - docker-compose -f docker/docker-compose.yml build

before_script:
  - docker-compose -f docker/docker-compose.yml up -d
  - yarn serve serve &

script:
  - yarn test
