language: node_js
dist: bionic
services:
  - docker

node_js:
  - 10

cache:
  directories:
    - node_modules
    - docker_images

before_install:
- docker load -i docker_images/images.tar || true

install:
  - yarn install --freeze
  - docker-compose -f docker/docker-compose.yml pull
  - docker-compose -f docker/docker-compose.yml build

before_script:
  - COMPOSE_HTTP_TIMEOUT=600 docker-compose -f docker/docker-compose.yml up -d
  - yarn serve serve &

script:
  - yarn test

before_cache:
- docker save -o docker_images/images.tar $(docker images -a -q)
