language: nodejs
dist: bionic
services: docker

node_js:
  - 12

install:
- npm install

before_script:
- docker-compose -f docker/docker-compose.yml pull
- docker-compose -f docker/docker-compose.yml build
- docker-compose -f docker/docker-compose.yml up -d
- npm run serve &

script:
- npm run test
