# This docker-compose file is for deploying a fully working backend

version: '3.7'

services:
    sqe-database:
        image: qumranica/sqe-database:0.23.2
        container_name: SQE_Database
        environment:
            ## These must be updated when used in production
            - MYSQL_ROOT_PASSWORD=none
            - MYSQL_USER=sqe_user
            - MYSQL_PASSWORD=mysecretpw
        expose:
            - "3306"
        ports:
            - "3307:3306"
        volumes:
            - sqe_api_db_volume:/var/lib/mysql
        networks:
            - sqe_api

    sqe-http:
        container_name: SQE_HTTP_API
        image: qumranica/sqe-http-api:0.10.1
        restart: always
        ports:
            - 5000:5000
        environment:
            ## Database settings (must match the settings for sqe-database above)
            - MYSQL_HOST=sqe-database # in docker-compose a service name can be used as a hostname (it will route to that container)
            - MYSQL_PORT=3306
            - MYSQL_USER=sqe_user
            - MYSQL_PASSWORD=mysecretpw
            - MYSQL_DATABASE=SQE
            
            ## Email settings (account that mails user registration information)
            - MAILER_EMAIL_ADDRESS
            - MAILER_EMAIL_USERNAME
            - MAILER_EMAIL_PASSWORD
            - MAILER_EMAIL_SMTP_URL
            - MAILER_EMAIL_SMTP_PORT
            - MAILER_EMAIL_SMTP_SECURITY=Auto #The options are "None", "Auto", "SslOnConnect", "StartTls", and "StartTlsWhenAvailable"
            
            ## Partner website settings (website that calls the user registration functions)
            - WEBSITE_HOST=http://localhost:8080              
            ## Dotnet telemetry optout
            - DOTNET_CLI_TELEMETRY_OPTOUT=1

            ## Logging levels, valid values are: Verbose, Debug, Information, Warning, Error, Fatal
            - API_LOGLEVEL=Information # Log level for API generated messages
            - DOTNET_LOGLEVEL=Warning # Log level for dotnet core messages and Microsoft tooling
            - SYSTEM_LOGLEVEL=Warning # Leg level for system level messages

            ## Redis SignalR backplane settings for horizontal scaling of the realtime API (disabled by default)
            - USE_REDIS=false # Use a Redis backplane to horizontally scale the realtime API
            #- REDIS_HOST=
            #- REDIS_PORT=
            #- REDIS_PASSWORD=

            ## Server options
            - Http_Server=true # Run the API HTTP server
              
            ## Secret string for API JWT generation (the API will error if this is too short)
            - SQE_API_SECRET=kjdsavc987342r8gnx%%6bq1@@lknsdciqeurhfwiurbcea-+++
        depends_on:
            - sqe-database
        networks:
            - sqe_api
        volumes:
            - ./logs:/app/logs

networks:
    sqe_api:

volumes:
    sqe_api_db_volume: