name: Frontend Tests
on:
    push:
        branches:
            - master
            - development
            - predevelopment
            - frontend-tests
    pull_request:
        branches:
            - master
            - development
            - predevelopment

jobs:
    frontend-tests:
        name: Frontend Tests
        runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install node
          uses: actions/setup-node@v2-beta
        - name: Setup environment
          runs: |
            yarn install --freeze
            yarn add wait-on
        - name: Run backend
          runs: |
            docker-compose -f docker/docker-compose.yml pull
            docker-compose -f docker/docker-compose.yml build
            COMPOSE_HTTP_TIMEOUT=600 docker-compose -f docker/docker-compose.yml up -d
            yarn serve & npx wait-on http://localhost:8080
        - name: Run tests
          runs: yarn test-ci

